services:
  myguide-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "4000:3000"
    restart: unless-stopped
    network_mode: bridge